services:
  - type: web
    name: shafnet-tours
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn shafnet_tours.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
