# Generated by Django 6.0.7 on 2026-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 3-Day Queen Elizabeth Safari', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the tour')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days')),
                ('location', models.CharField(help_text='e.g. Queen Elizabeth National Park', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload a nice photo', null=True, upload_to='tours/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
