# Generated by Django 6.0.7 on 2026-07-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.CharField(blank=True, choices=[('central', 'Central Uganda'), ('western', 'Western Uganda'), ('northern', 'Northern Uganda'), ('eastern', 'Eastern Uganda')], help_text='Only for International Safaris', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='target_audience',
            field=models.CharField(choices=[('domestic', 'Domestic Tours'), ('international', 'International Safaris')], default='international', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
