# Generated by Django 6.0.7 on 2026-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.CharField(blank=True, choices=[('central', 'Central Uganda'), ('western', 'Western Uganda'), ('northern', 'Northern Uganda'), ('eastern', 'Eastern Uganda')], max_length=20, null=True),
        ),
    ]
